### ISSUE TITLE
‼️ Notice: Upcoming Breaking Changes in v4

### ISSUE THREAD

**Issue by mrgrain** [mrgrain/cdk-esbuild#202]
No timeline for a v4 release yet, but this list will hold all planned breaking changes. Feedback welcome!

### API changes
- [x] Check `buildFn` , `esbuildBinaryPath`, `esbuildModulePath` -> unified interface! #286
- [x] Better error handling, i.e. throw on build failure in bundler. Can the messages be improved?
  `bundler.ts` should throw like InlineCode on error #239 
- [x] Change default format of InlineCode to `cjs` #282 

### Removal of deprecated features
- [x] in `InlineXCodeProps` remove `TransformOptions` #281 

### Experimental features
- [x] graduate `InlineXCode`, remove `InlineTsxCode` and `InlineJsxCode` #283 

### Other
- [x] ~Compress jsii~ won't do. The size savings are minimal but there's some speed penalty for extracting the compressed assembly
