### ISSUE TITLE
‼️ Notice: Breaking Changes in v5

### ISSUE THREAD

**Issue by mrgrain** [mrgrain/cdk-esbuild#732]
### API changes to stable features
- [x] The JavaScript versions of all classes have been removed. They have been functionally identical to the TypeScript versions since the beginning. Please use the TypeScript versions of the classes going forward. #665

### Experimental features
- [x] Low-level experimental classes EsbuildAsset and EsbuildCode have been removed. Please use TypeScriptAsset and TypeScriptCode respectively. #665

### Other breaking changes
- [x] Drop support for node14 and node16 #718
- [x] Lift minimum version requirement of `aws-cdk` to 2.51.0 #730
- [x] Build with jsii@5.1 and typescript@5.1 #665

### Removal of deprecated features
None
